### ISSUE TITLE
Bulk write

### ISSUE THREAD

**Issue by NGSalvo** [tinyerp/erppeek#105]
Hi, it's possible to bulk write in order to not make many queries to the DB. What I would like to do is something like:
browse_product.write(values)
Where browse_product is a RecordList and values is a list of dict, so I can pass different values to the recordlist.
Example:
values: [{'standard_price': 350}, {'standard_price': 453, 'active': true}]
whereas there are 2 records in the list.

**Comment by florentx** [comment]
As far as I know this kind of write is not supported by Odoo internal API.

Also for your new projects, I suggest to switch to Odooly: https://github.com/tinyerp/odooly

**Comment by NGSalvo** [comment]
I'll do that on a next iteration. If just switch, my API would break, 'cause the breaking changes.
Thanks.
