### ISSUE TITLE
create quotation or invoices?

### ISSUE THREAD

**Issue by ericmachine88** [tinyerp/erppeek#39]
Like to check how much I could do with erppeek? Is it production ready?

Can I create a new draft quotation, then send for approval, etc? 

Same to invoices creation?

Any help? Thanks.

**Comment by opmauryasarthi** [comment]
Integrity Error

The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: y1= - y1=]

**Comment by opmauryasarthi** [comment]
Please help me
thanks in advance
