### ISSUE TITLE
unicode representation for record

### ISSUE THREAD

**Issue by xblitz** [tinyerp/erppeek#74]
example: direct printing of a record that has unicode data:

    print record
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)

since the Record does not implement __unicode__  and data received by the server (xmlrpc) is in unicode (utf8) 

i think the code in Record should look like

    def __unicode__(self):
        return self._name

    def __str__(self):
        return self._name.encode('ascii', 'replace')

**Comment by florentx** [comment]
thank you.

I will adapt to support 2.7 and 3.x ...

Interesting reading .... http://kmike.ru/python-with-strings-attached/

**Comment by florentx** [comment]
I've merged the fix for 1.6.2
