### ISSUE TITLE
How to dump and restore?

### ISSUE THREAD

**Issue by ericmachine88** [tinyerp/erppeek#75]
Any idea how I could dump and restore via erppeek?

I like the idea of installing modules but it would be way faster to dump (backup) and restore it.

Any help? Thanks.

**Comment by florentx** [comment]
SQL dump? it's more direct and faster ... and out of the scope of ERPpeek

**Comment by ericmachine88** [comment]
yeah, you are right :)

anyway i am using fabric now :)
