### ISSUE TITLE
Pouvoir faire un "execute" sans "context"

### ISSUE THREAD

**Issue by bdanna** [tinyerp/erppeek#80]
Certaines fonctions, du moins dans le code de la v7, n'ont pas forcément de paramètre "context".
Ex : procurement.py :     def action_done(self, cr, uid, ids):
Or le wrapper du Client d'Erppeek force sa présence : 
`def wrapper(self, *params, **kwargs):`
`"""Wrapper for client.execute(%r, %r, *params, **kwargs)."""`
`if 'context' not in kwargs:`
`kwargs['context'] = self.client.context`
`return self._execute(attr, *params, **kwargs)`

Et comme c'est une fonction dans une méthode, je ne sais pas surcharger cette fonction.
Est-ce que wrapper pourrait aussi être une méthode surchargeable ou bien est-ce que ce "forcage" pourrait être optionnel ?

**Comment by xblitz** [comment]
probably would help if you write this in english

**Comment by yvaucher** [comment]
@bdanna Can't you pass an empty context ?

**Comment by florentx** [comment]
sorry for the late reply.

You can always pass an `context=None`, and it will not be sent to the API.
As an alternative, you can set `client.context = None` to unset the default context.

**Comment by xblitz** [comment]
![71aye](https://user-images.githubusercontent.com/592097/48856908-a3d6d980-ed85-11e8-9b16-6d68b55962fb.jpg)
