### ISSUE TITLE
update_list() in _upgrade method not works

### ISSUE THREAD

**Issue by kurkop** [tinyerp/erppeek#83]
Hi,

I'am testing Erppeek and I found that when I add a new module to addons folder and I want install other module (as dependencies) not install and fail: **But the latter module is not available in your system**.
This ocurrs because the module list isn't updated.

https://github.com/tinyerp/erppeek/blob/master/erppeek.py#L760

**Comment by yvaucher** [comment]
Hi @kurkop ,

This is because you need to do a "module update list". You can call the method 

`update_list()` of model `ir.module.module`
