### ISSUE TITLE
How to execute a sql query?

### ISSUE THREAD

**Issue by jweste** [tinyerp/erppeek#93]
Hi,

I'd like to execute a sql query via erppeek, but I'm not sure how to do it.
I wrote a .py file that connects to my server with the following code

```
def init_openerp(url, login, password, database):
    try:
        openerp = erppeek.Client(url)
        uid = openerp.login(login, password=password, database=database)
        return openerp, uid
    except:
        return False, False
```
Then, my idea was to get the cursor of the db, to use the Cursor.execute() method. But I don't manage to get the cursor.

I read that 
> The cursor factory is available on the registry as get_pool().cursor() (Odoo) or get_pool().db.cursor() (OpenERP <= 7).

But this doesn't work. Can anyone tell me the correct syntax? Or the correct way to execute sql query?
Thanks!

**Comment by sebastienbeau** [comment]
HI Julien
It's not possible to execute sql request using the odoo api webservice as it will be a security issue as sql request bypass the ORM.
So there is noway with erpeek or any other odoo client to execute sql

**Comment by florentx** [comment]
I confirm that you can only use a Cursor if you load the server configuration and connect in `local` mode.
