### ISSUE TITLE
*** AttributeError: 'unicode' object has no attribute '_api_v7'

### ISSUE THREAD

**Issue by shepilov-vladislav** [tinyerp/erppeek#98]
```
>>> type(server)
<type 'unicode'>
client = erppeek.Client(
        server, db, user, password, transport=None, verbose=False
)
```

Raised error:
`*** AttributeError: 'unicode' object has no attribute '_api_v7'`

**Comment by oducrot** [comment]
Hi,

I had the same issue. It's due to the python version detection.

**Comment by oducrot** [comment]
try:                    # Python 3
    import configparser
    from threading import current_thread
    from xmlrpc.client import Fault, ServerProxy, MININT, MAXINT
    PY2 = False
except ImportError:     # Python 2
    import ConfigParser as configparser
    from threading import currentThread as current_thread
    from xmlrpclib import Fault, ServerProxy, MININT, MAXINT
    PY2 = True

**Comment by oducrot** [comment]
the detection is made with the error generated trying to import modules. But configparser exists for python 2 and 3. If it's installed, erppeek detects python 3 and PY2= false. Cleanup your packages or change the way PY2 is defined with : PY2 = (sys.version_info[0] == 2)

**Comment by florentx** [comment]
Fixed in master branch
